-- 코드를 입력하세요
SELECT  YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER, COUNT(DISTINCT USER_ID)AS "USERS"
FROM    ONLINE_SALE JOIN USER_INFO USING (USER_ID)
WHERE   GENDER IS NOT NULL
GROUP   BY 1,2,3
ORDER   BY  1,2,3