-- 코드를 입력하세요
SELECT  AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE)
FROM    BOOK B JOIN AUTHOR A USING (AUTHOR_ID)
        JOIN BOOK_SALES S USING (BOOK_ID)
WHERE   YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP   BY 1,2,3
ORDER   BY 1 ASC, 3 DESC